### ISSUE TITLE
Authentication Functionnality

### ISSUE THREAD

**Issue by red1code** [red1code/testing-only#1]
Implement all necessary authentication functionality for the app.

# TODO:

- [ ] User can sign up using a valid email and password
- [ ] He can login afterwards using the same credentials 
- [ ] User can logout
- [ ] User can ask for a password reset if the current password is forgotten
